services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./models:/app/models
    depends_on:
      - minio
    environment:
      - PYTHONUNBUFFERED=1
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"          # MinIO console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data: