FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1

# Dependencias
COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Código
COPY app .

# Start
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]